CREATE TABLE NOBEL.CATEGORIES
(
  CATEGORY_ID  NUMBER                           NOT NULL,
  CATEGORY     VARCHAR2(100 BYTE),
  PRIZE_NAME   VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.COUNTRIES
(
  COUNTRY_ID  NUMBER                            NOT NULL,
  COUNTRY     VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.FIELDS
(
  FIELD_ID  NUMBER                              NOT NULL,
  FIELD     VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.PRICE_WINNERS
(
  PRIZE_WINNERS_ID  NUMBER                      NOT NULL,
  PRIZE_ID          NUMBER,
  PERSON_ID         NUMBER,
  COUNTRY_ID        NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.PRIZE
(
  PRIZE_ID     NUMBER                           NOT NULL,
  PRIZE_YEAR   INTEGER,
  FIELD_ID     NUMBER,
  CATEGORY_ID  NUMBER,
  MOTIVATION   VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.ROLES
(
  ROLE_ID    NUMBER                             NOT NULL,
  AFFILIATE  VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE TABLE NOBEL.WINNERS
(
  PERSON_ID   NUMBER                            NOT NULL,
  NAME        VARCHAR2(100 BYTE),
  BIRTHDATE   DATE,
  ROLE_ID     NUMBER,
  BIRTHPLACE  VARCHAR2(100 BYTE),
  RESIDENCE   VARCHAR2(100 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX NOBEL.CATEGORIES_PK ON NOBEL.CATEGORIES
(CATEGORY_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.COUNTRIES_PK ON NOBEL.COUNTRIES
(COUNTRY_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.FIELDS_PK ON NOBEL.FIELDS
(FIELD_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.PRICE_WINNERS_PK ON NOBEL.PRICE_WINNERS
(PRIZE_WINNERS_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.PRIZE_PK ON NOBEL.PRIZE
(PRIZE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.ROLES_PK ON NOBEL.ROLES
(ROLE_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX NOBEL.WINNERS_PK ON NOBEL.WINNERS
(PERSON_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE NOBEL.CATEGORIES ADD (
  CONSTRAINT CATEGORIES_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX NOBEL.CATEGORIES_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.COUNTRIES ADD (
  CONSTRAINT COUNTRIES_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX NOBEL.COUNTRIES_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.FIELDS ADD (
  CONSTRAINT FIELDS_PK
  PRIMARY KEY
  (FIELD_ID)
  USING INDEX NOBEL.FIELDS_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRICE_WINNERS ADD (
  CONSTRAINT PRICE_WINNERS_PK
  PRIMARY KEY
  (PRIZE_WINNERS_ID)
  USING INDEX NOBEL.PRICE_WINNERS_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRIZE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  USING INDEX NOBEL.PRIZE_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.ROLES ADD (
  CONSTRAINT ROLES_PK
  PRIMARY KEY
  (ROLE_ID)
  USING INDEX NOBEL.ROLES_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.WINNERS ADD (
  CONSTRAINT WINNERS_PK
  PRIMARY KEY
  (PERSON_ID)
  USING INDEX NOBEL.WINNERS_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRIZE ADD (
  CONSTRAINT PRIZE_R01 
  FOREIGN KEY (FIELD_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);

ALTER TABLE NOBEL.CATEGORIES ADD (
  CONSTRAINT CATEGORIES_PK
  PRIMARY KEY
  (CATEGORY_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.COUNTRIES ADD (
  CONSTRAINT COUNTRIES_PK
  PRIMARY KEY
  (COUNTRY_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.FIELDS ADD (
  CONSTRAINT FIELDS_PK
  PRIMARY KEY
  (FIELD_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.PRICE_WINNERS ADD (
  CONSTRAINT PRICE_WINNERS_PK
  PRIMARY KEY
  (PRIZE_WINNERS_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.PRIZE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.ROLES ADD (
  CONSTRAINT ROLES_PK
  PRIMARY KEY
  (ROLE_ID)
  ENABLE VALIDATE);


ALTER TABLE NOBEL.PRICE_WINNERS ADD (
  CONSTRAINT PRICE_WINNERS_R01 
  FOREIGN KEY (PRIZE_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRICE_WINNERS ADD (
  CONSTRAINT PRICE_WINNERS_R02 
  FOREIGN KEY (PERSON_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRICE_WINNERS ADD (
  CONSTRAINT PRICE_WINNERS_R03 
  FOREIGN KEY (COUNTRY_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);


ALTER TABLE NOBEL.PRIZE ADD (
  CONSTRAINT PRIZE_R01 
  FOREIGN KEY (FIELD_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PRIZE ADD (
  CONSTRAINT PRIZE_R02 
  FOREIGN KEY (CATEGORY_ID) 
  REFERENCES NOBEL.
  ENABLE VALIDATE);

CREATE SEQUENCE NOBEL.CATEGORY_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.COUNTRY_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.FIELDS_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.PERSON_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.PRIZE_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.PRIZE_WINNERS_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE NOBEL.ROLES_SEQ
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;